### ISSUE TITLE
installNpmRevision failing when running on-premise

### ISSUE THREAD

**Issue by firefoxNX** [apigeecs/apigee-deploy-grunt-plugin#14]
When running the grunt plugin against on-premise install I am getting below error. Looks like the API request did not get created properly? Despite the error, in apigee management console I can see the api-proxy got deployed correctly.

```
[4mRunning "installNpmRevision" task[24m
[D] [35mTask source: grunt/tasks/installNpmRevision.js[39m
curl -X POST -u user@OrgName.com:**** -H 'Content-Type: application/x-www-form-urlencoded' -v https://http::443//10.x.y.z:8080/v1/o/OrgName/apis/build-test/revisions/7/npm
[D] [35m500[39m
[D] [35mnpm ERR! 	at /opt/apigee4/share/apigee/lib/node_modules/npm/node_modules/lockfile/lockfile.js:182 (anonymous)
npm ERR! 	at /Users/Apigee/src/noderunner/target/checkout/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/fs.js:107 (anonymous)
npm ERR! 	at /Users/Apigee/src/noderunner/target/checkout/node10/node10src/src/main/javascript/io/apigee/trireme/node10/main/trireme.js:816 (submitDomainTick)
npm ERR! 
npm ERR! If you need help, you may report this [1mentire[22m log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Trireme Trireme
npm ERR! command "./node" "/opt/apigee4/share/apigee/lib/node_modules/npm/cli.js" "--loglevel" "error" "--registry" "https://registry.npmjs.org/" "--cache" "/opt/apigee4/var/log/apigee/management-server/work/npm-cache" "--ignore-scripts" "true" "--bin-links" "false" "--json" "install"
npm ERR! cwd /opt/apigee4/var/log/apigee/management-server/work/npm/npm7718831451012383918.tmp
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.4.3
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/apigee4/var/log/apigee/management-server/work/npm/npm7718831451012383918.tmp/npm-debug.log
npm ERR! not ok code 0
[39m
[33mWarning: Task "installNpmRevision" failed. [4mUsed --force, continuing.[24m[39m
```

**Comment by dzuluaga** [comment]
Thanks, Vinit. It looks like it's trying to run it with Trireme v0.10.24, which seems quite old, instead of plain old Node.js. I haven't tested on this version because typically Jenkins or Travis machines can run native Node.js. Would you mind trying it on a native Node.js from either your laptop or on another machine connected to the server?

BTW - You might want to try this when you get a chance. https://github.com/dzuluaga/generator-apigee-deploy-grunt-api

**Comment by firefoxNX** [comment]
I don't have trireme installed. See complete grunt output - https://gist.github.com/firefoxNX/772cf5a6452a0eb813e9

Yes! We are making use of yo generator as well and its awesome! Thank You for creating the apigee plugin and yo generator.

**Comment by dzuluaga** [comment]
I agree. It looks weird cURL command
"https://http::443//10.x.y.z:8080/v1/o/OrgName/apis/build-test/revisions/7/npm".
I'd try these steps to try to troubleshoot it:

1) Check the Management URL
<https://github.com/apigeecs/apigee-deploy-grunt-plugin/blob/master/grunt/apigee-config.js#L8>
and
compare with others requests above to see if it's similar.
2) If the URL in the requests above are different, then it's possible the
SDK is for some reason generating the URL different than other requests.
Here's
<https://http::443//10.x.y.z:8080/v1/o/OrgName/apis/build-test/revisions/7/npm>
where it gets generated.

I'll try to troubleshoot it myself, but it might take me longer since I
need an OPDK instance on my laptop and it's quite late here. However, I've
used with other customer with no problem. Let's try to sync up tomorrow.
I'm in UK, so we can try a gotomeeting in the afternoon.

BTW - what customer is this for?

Regards,
Diego

On Mon, Mar 23, 2015 at 10:43 PM, Vineet Bhatia <notifications@github.com>
wrote:

> I don't have trireme installed. See complete grunt output -
> https://gist.github.com/firefoxNX/772cf5a6452a0eb813e9
>
> Yes! We are making use of yo generator as well and its awesome! Thank You
> for creating the apigee plugin and yo generator.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apigeecs/apigee-deploy-grunt-plugin/issues/14#issuecomment-85235906>
> .
>



-- 
Diego Zuluaga | apigee <http://www.apigee.com/> | m: +1.416.509.2327 | twitter
@dzuluaga <http://twitter.com/dzuluaga> @apigee <https://twitter.com/apigee>
| skype dzuluaga | *Apigee Community <http://community.apigee.com/>* for
answers, ideas and support!

**Comment by firefoxNX** [comment]
1) looks correct as the other tasks work fine.

```
'dev' : {
				apiproxy : 'build-test',
					org : 'OrgName', // replace with organization
					env : 'dev',     // replace with environment
					url_mgmt : 'http://10.xx.xx.xx:8080',  // for cloud environments, leave as is
					username : grunt.option('username'), //|| process.env.ae_username, // pass credentials as arguments as grunt task --username=$ae_username --password=$ae_password
					password : grunt.option('password'), //|| process.env.ae_password, // use ae_username and ae_password are defined as environment variables and no arguments are passed
					revision : grunt.option('revision'), // provide revision to be undeployed by passing argument as --revision=X
					override : grunt.option('override') || false,
					delay : grunt.option('delay') || 0
				}
```

2) See https://gist.github.com/firefoxNX/3e837d43c19e0434b6ec which has the curl output as well.

3) Versions of node and npm

$ node -v
v0.12.0

$ npm -v
2.7.3

**Comment by dzuluaga** [comment]
Interesting. I'd like to try the REST API directly and see if you get the
same error, which is what installNpmRevision task is effectively doing.

curl
https://api.enterprise.apigee.com/v1/organizations/{org}/apis/{api-name}/revisions/{revision-id}/npm?verbose=true
-H 'Content-Type:application/x-www-form-urlencoded' -d 'command=install' -u
$ae_username:$ae_password

if you do so, I wonder if what's causing the issue is for any reason a
dependency in package.json. Please check removing dependencies from it.



On Tue, Mar 24, 2015 at 12:50 AM, Vineet Bhatia <notifications@github.com>
wrote:

> 1) looks correct as the other tasks work fine.
>
> 'dev' : {
>                 apiproxy : 'build-test',
>                     org : 'OrgName', // replace with organization
>                     env : 'dev',     // replace with environment
>                     url_mgmt : 'http://10.xx.xx.xx:8080',  // for cloud environments, leave as is
>                     username : grunt.option('username'), //|| process.env.ae_username, // pass credentials as arguments as grunt task --username=$ae_username --password=$ae_password
>                     password : grunt.option('password'), //|| process.env.ae_password, // use ae_username and ae_password are defined as environment variables and no arguments are passed
>                     revision : grunt.option('revision'), // provide revision to be undeployed by passing argument as --revision=X
>                     override : grunt.option('override') || false,
>                     delay : grunt.option('delay') || 0
>                 }
>
> 2) See https://gist.github.com/firefoxNX/3e837d43c19e0434b6ec which has
> the curl output as well.
>
> 3) Versions of node and npm
>
> $ node -v
> v0.12.0
>
> $ npm -v
> 2.7.3
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apigeecs/apigee-deploy-grunt-plugin/issues/14#issuecomment-85267164>
> .
>



-- 
Diego Zuluaga | apigee <http://www.apigee.com/> | m: +1.416.509.2327 | twitter
@dzuluaga <http://twitter.com/dzuluaga> @apigee <https://twitter.com/apigee>
| skype dzuluaga | *Apigee Community <http://community.apigee.com/>* for
answers, ideas and support!

**Comment by firefoxNX** [comment]
Thanks! Looks like issue could be with specific version of on-premise apigee?

1) Output of install curl command
```
$ curl -X POST -u username@orgname.com:xxxx -H 'Content-Type: application/x-www-form-urlencoded' -v http://10.xx.xx.xx:8080/v1/o/orgname/apis/build-test/revisions/2/npm?verbose=true -d 'command=install'
* Hostname was NOT found in DNS cache
*   Trying 10.xx.xx.xx...
* Connected to 10.xx.xx.xx (10.xx.xx.xx) port 8080 (#0)
* Server auth using Basic with user 'username@orgname.com'
> POST /v1/o/orgname/apis/build-test/revisions/2/npm?verbose=true HTTP/1.1
> Authorization: Basic xxxxx=
> User-Agent: curl/7.37.1
> Host: 10.34.42.61:8080
> Accept: */*
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 15
> 
* upload completely sent off: 15 out of 15 bytes
< HTTP/1.1 500 Server Error
< Content-Type: text/plain
< Date: Tue, 24 Mar 2015 13:34:49 GMT
< Content-Length: 1242
* Server Jetty(8.0.4.v20111024) is not blacklisted
< Server: Jetty(8.0.4.v20111024)
< 
npm ERR! 	at /opt/apigee4/share/apigee/lib/node_modules/npm/node_modules/lockfile/lockfile.js:182 (anonymous)
npm ERR! 	at /Users/Apigee/src/noderunner/target/checkout/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/fs.js:107 (anonymous)
npm ERR! 	at /Users/Apigee/src/noderunner/target/checkout/node10/node10src/src/main/javascript/io/apigee/trireme/node10/main/trireme.js:816 (submitDomainTick)
npm ERR! 
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Trireme Trireme
npm ERR! command "./node" "/opt/apigee4/share/apigee/lib/node_modules/npm/cli.js" "--loglevel" "error" "--registry" "https://registry.npmjs.org/" "--cache" "/opt/apigee4/var/log/apigee/management-server/work/npm-cache" "--ignore-scripts" "true" "--bin-links" "false" "--json" "install"
npm ERR! cwd /opt/apigee4/var/log/apigee/management-server/work/npm/npm6052630849682313473.tmp
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.4.3
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/apigee4/var/log/apigee/management-server/work/npm/npm6052630849682313473.tmp/npm-debug.log
npm ERR! not ok code 0
* Connection #0 to host 10.34.42.61 left intact
```

I will post the npm logs as well in few minutes.

2) I have not added any other dependencies in package.son

```
{
  "name": "build-test",
  "version": "0.0.1",
  "description": "Out of the box I include scaffolding apiproxy, Node.js, and Gruntfile to build your app.",
  "main": "index.js",
  "scripts": {
    "test": "grunt mochaTest -env=test"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/apigeecs/build-test"
  },
  "keywords": [
    "apigee",
    "deploy",
    "lifecycle",
    "API"
  ],
  "author": "{YOUR_NAME_HERE}",
  "license": "ISC",
  "dependencies": {
    "apigee-sdk-mgmt-api": "^1.1.0",
    "async": "^0.9.0",
    "blanket": "^1.1.6",
    "chai": "^1.9.1",
    "chai-http": "^1.0.0",
    "curl-cmd": "0.0.0",
    "gift": "^0.4.3-1",
    "grunt": "^0.4.5",
    "grunt-available-tasks": "^0.5.0",
    "grunt-complexity": "^0.2.0",
    "grunt-contrib-clean": "^0.5.0",
    "grunt-contrib-compress": "^0.12.0",
    "grunt-contrib-concat": "^0.5.0",
    "grunt-contrib-copy": "^0.5.0",
    "grunt-contrib-jshint": "^0.10.0",
    "grunt-eslint": "^1.0.0",
    "grunt-mkdir": "^0.1.2",
    "grunt-mocha-test": "^0.11.0",
    "grunt-notify": "^0.3.1",
    "grunt-shell": "^1.1.1",
    "grunt-string-replace": "^1.0.0",
    "grunt-update-submodules": "^0.4.1",
    "grunt-xmlpoke": "^0.6.0",
    "jshint-stylish": "^0.4.0",
    "load-grunt-config": "^0.12.0",
    "load-grunt-tasks": "^0.6.0",
    "request": "^2.37.0",
    "time-grunt": "^1.0.0"
  },
  "devDependencies": {}
}
```

**Comment by dzuluaga** [comment]
Sorry, I meant the package.json within node folder, instead of the root
folder. Also before concluding it's an issue with the OPDK build, I'd
suggest checking that a the Hello World API proxy is deployable with
installNpmRevision. If there are no third party modules causing this issue,
the third option is to package node_modules folder before deploying the
bundle and deactivating installNpmRevision. To try this uncomment this
section
<https://github.com/apigeecs/apigee-deploy-grunt-plugin/blob/master/Gruntfile.js#L69-L77>
and
commenting installNpmRevision below in the Gruntfile.js. If this works,
this would be a sign there's something going on the build or configuration
as the API call is supposed to work. Let me know how it goes.

On Tue, Mar 24, 2015 at 1:45 PM, Vineet Bhatia <notifications@github.com>
wrote:

> Thanks! Looks like issue could be with specific version of on-premise
> apigee?
>
> 1) Output of install curl command
>
> $ curl -X POST -u username@orgname.com:xxxx -H 'Content-Type: application/x-www-form-urlencoded' -v http://10.xx.xx.xx:8080/v1/o/orgname/apis/build-test/revisions/2/npm?verbose=true -d 'command=install'
> * Hostname was NOT found in DNS cache
> *   Trying 10.xx.xx.xx...
> * Connected to 10.xx.xx.xx (10.xx.xx.xx) port 8080 (#0)
> * Server auth using Basic with user 'username@orgname.com'
> > POST /v1/o/orgname/apis/build-test/revisions/2/npm?verbose=true HTTP/1.1
> > Authorization: Basic xxxxx=
> > User-Agent: curl/7.37.1
> > Host: 10.34.42.61:8080
> > Accept: */*
> > Content-Type: application/x-www-form-urlencoded
> > Content-Length: 15
> >
> * upload completely sent off: 15 out of 15 bytes
> < HTTP/1.1 500 Server Error
> < Content-Type: text/plain
> < Date: Tue, 24 Mar 2015 13:34:49 GMT
> < Content-Length: 1242
> * Server Jetty(8.0.4.v20111024) is not blacklisted
> < Server: Jetty(8.0.4.v20111024)
> <
> npm ERR!    at /opt/apigee4/share/apigee/lib/node_modules/npm/node_modules/lockfile/lockfile.js:182 (anonymous)
> npm ERR!    at /Users/Apigee/src/noderunner/target/checkout/node10/node10src/src/main/javascript/io/apigee/trireme/node10/node/fs.js:107 (anonymous)
> npm ERR!    at /Users/Apigee/src/noderunner/target/checkout/node10/node10src/src/main/javascript/io/apigee/trireme/node10/main/trireme.js:816 (submitDomainTick)
> npm ERR!
> npm ERR! If you need help, you may report this *entire* log,
> npm ERR! including the npm and node versions, at:
> npm ERR!     <http://github.com/npm/npm/issues>
>
> npm ERR! System Trireme Trireme
> npm ERR! command "./node" "/opt/apigee4/share/apigee/lib/node_modules/npm/cli.js" "--loglevel" "error" "--registry" "https://registry.npmjs.org/" "--cache" "/opt/apigee4/var/log/apigee/management-server/work/npm-cache" "--ignore-scripts" "true" "--bin-links" "false" "--json" "install"
> npm ERR! cwd /opt/apigee4/var/log/apigee/management-server/work/npm/npm6052630849682313473.tmp
> npm ERR! node -v v0.10.24
> npm ERR! npm -v 1.4.3
> npm ERR!
> npm ERR! Additional logging details can be found in:
> npm ERR!     /opt/apigee4/var/log/apigee/management-server/work/npm/npm6052630849682313473.tmp/npm-debug.log
> npm ERR! not ok code 0
> * Connection #0 to host 10.34.42.61 left intact
>
> I will post the npm logs as well in few minutes.
>
> 2) I have not added any other dependencies in package.son
>
> {
>   "name": "build-test",
>   "version": "0.0.1",
>   "description": "Out of the box I include scaffolding apiproxy, Node.js, and Gruntfile to build your app.",
>   "main": "index.js",
>   "scripts": {
>     "test": "grunt mochaTest -env=test"
>   },
>   "repository": {
>     "type": "git",
>     "url": "https://github.com/apigeecs/build-test"
>   },
>   "keywords": [
>     "apigee",
>     "deploy",
>     "lifecycle",
>     "API"
>   ],
>   "author": "{YOUR_NAME_HERE}",
>   "license": "ISC",
>   "dependencies": {
>     "apigee-sdk-mgmt-api": "^1.1.0",
>     "async": "^0.9.0",
>     "blanket": "^1.1.6",
>     "chai": "^1.9.1",
>     "chai-http": "^1.0.0",
>     "curl-cmd": "0.0.0",
>     "gift": "^0.4.3-1",
>     "grunt": "^0.4.5",
>     "grunt-available-tasks": "^0.5.0",
>     "grunt-complexity": "^0.2.0",
>     "grunt-contrib-clean": "^0.5.0",
>     "grunt-contrib-compress": "^0.12.0",
>     "grunt-contrib-concat": "^0.5.0",
>     "grunt-contrib-copy": "^0.5.0",
>     "grunt-contrib-jshint": "^0.10.0",
>     "grunt-eslint": "^1.0.0",
>     "grunt-mkdir": "^0.1.2",
>     "grunt-mocha-test": "^0.11.0",
>     "grunt-notify": "^0.3.1",
>     "grunt-shell": "^1.1.1",
>     "grunt-string-replace": "^1.0.0",
>     "grunt-update-submodules": "^0.4.1",
>     "grunt-xmlpoke": "^0.6.0",
>     "jshint-stylish": "^0.4.0",
>     "load-grunt-config": "^0.12.0",
>     "load-grunt-tasks": "^0.6.0",
>     "request": "^2.37.0",
>     "time-grunt": "^1.0.0"
>   },
>   "devDependencies": {}
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apigeecs/apigee-deploy-grunt-plugin/issues/14#issuecomment-85501861>
> .
>



-- 
Diego Zuluaga | apigee <http://www.apigee.com/> | m: +1.416.509.2327 | twitter
@dzuluaga <http://twitter.com/dzuluaga> @apigee <https://twitter.com/apigee>
| skype dzuluaga | *Apigee Community <http://community.apigee.com/>* for
answers, ideas and support!

**Comment by firefoxNX** [comment]
Uncommenting Gruntfile.js#L69-L77 and commenting installNpmRevision worked!

package.json in node folder
```
{
  "name": "express-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "path": "^0.4.9"
  }
}
```

**Comment by dzuluaga** [comment]
Cool. I'm glad it worked! That package.json looks pretty lean. I doubt
there's an issue with that, so perhaps there's something going on the
server. It might be worth investigating. Let me know if you have any
questions. Also, I you find bugs or improvements to any of the tools, feel
free to fork the repo and submit a pull request.

Regards,
Diego

On Tue, Mar 24, 2015 at 2:49 PM, Vineet Bhatia <notifications@github.com>
wrote:

> Uncommenting Gruntfile.js#L69-L77 and commenting installNpmRevision worked!
>
> package.json in node folder
>
> {
>   "name": "express-test",
>   "version": "1.0.0",
>   "description": "",
>   "main": "index.js",
>   "scripts": {
>     "test": "echo \"Error: no test specified\" && exit 1"
>   },
>   "author": "",
>   "license": "ISC",
>   "devDependencies": {
>     "path": "^0.4.9"
>   }
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/apigeecs/apigee-deploy-grunt-plugin/issues/14#issuecomment-85537505>
> .
>



-- 
Diego Zuluaga | apigee <http://www.apigee.com/> | m: +1.416.509.2327 | twitter
@dzuluaga <http://twitter.com/dzuluaga> @apigee <https://twitter.com/apigee>
| skype dzuluaga | *Apigee Community <http://community.apigee.com/>* for
answers, ideas and support!
